Moviement/Moviement/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = "home"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('movies.urls'),name="homepage"),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Moviement/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

Moviement/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('',views.movies_list,name="list"),
    path('search/',views.search_results.as_view(),name="search_results"),
    path('<slug:slug>/',views.movie_detail,name="detail"),
]

Moviement/accounts/models.py
from django.db import models

# Create your models here.

Moviement/movies/models.py
from django.db import models
from django.db.models.fields import DurationField

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=100)
    duration = models.DurationField()
    year = models.DateField(auto_now_add=True)
    thumb = models.ImageField()
    slug = models.SlugField()
    story = models.TextField()
    video = models.FileField()

    def __str__(self):
        return self.title

Moviement/Moviement/views.py
from django.shortcuts import render

def homepage(request):
    return render(request,'base_layout.html')

Moviement/accounts/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('movies:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POSt.get('next'))
            else:
                return redirect('movies:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('movies:list')

Moviement/movies/views.py
from django.db.models import query
from django.http import request
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Movie
from django.db.models import Q
from django.views.generic import TemplateView, ListView


# Create your views here.

def movies_list(request):
    movies = Movie.objects.all().order_by('year')
    return render(request,'movies_list.html',{'movies': movies})

def movie_detail(request, slug):
    movie = Movie.objects.get(slug=slug)
    return render(request,'movie_detail.html',{'movie':movie})


class search_results(ListView):
    model = Movie
    template_name = 'search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get('que')
        object_list = Movie.objects.filter(
            Q(title__icontains=query) | Q(slug__icontains=query)
        )
        return object_list

Moviement/accounts/templates/accounts/login.html
{% extends 'most_basic_layout.html' %}

{% block content %}
    <div class="form-container">
        <form class="site-form" action="/accounts/login/" method="post" >
            <h1 style="color: red;">Login Form</h1>
            {% csrf_token %}
            {{form}}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
            {% endif %}
            <input class="submit-button" type="submit" value="Login">
        </form>
    </div>
{% endblock %}

Moviement/accounts/templates/accounts/signup.html
{% extends 'most_basic_layout.html' %}

{% block content %}
    <div class="form-container">
        <form class="site-form" action="/accounts/signup/" method="post">
            <h1 style="color: red;">Signup Form</h1>
            {% csrf_token %}
            {{form}}
            <input class="submit-button" type="submit" value="Singup">
        </form>
    </div>
{% endblock %}

Moviement/movies/templates/movie_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="movie">
        <div class="movie_details">
            <h1 class="movie_title">{{movie.title}}</h1>
            <h2 class="timings">{{movie.duration}} | {{movie.year}}</h2>
            <h3 class="movie_story">{{movie.story}}</h6>
    
        </div>
        <div class="movie_video">
            <video width="100%" height="auto" controls>
                <source src="{{ movie.video.url }}" type="video/mp4">
            </video>
        </div>
    </div>
{% endblock %}

Moviement/movies/templates/movies_list.html
{% extends 'base_layout.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <!-- <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">     -->
    <h1 style="padding: 0 20px;">Trending....</h1>
        <div style="line-height: 0;
                                -webkit-column-count:4; /* split it into 5 columns */
                                -webkit-column-gap:8px; /* give it a 5px gap between columns */
                                -moz-column-count:4;
                                -moz-column-gap:8px;
                                column-count:4;
                                column-gap:8px;
                                padding: 0 20px;
                                backdrop-filter: blur(2000px);">
            {% for movie in movies %}
                <div>
                    <a href="{% url 'movies:detail' slug=movie.slug %}">
                        <img src="{{movie.thumb.url}}" style="width: 100% ;
                                                            height: auto ;
                                                            margin-bottom:  8px;
                                                            cursor: pointer;
                                                            border: 1px solid white;" >
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

Moviement/movies/templates/search_results.html
{% extends 'base_layout.html' %}

{% block content %}
    {% if object_list.all %}
    <div style="line-height: 0;
                -webkit-column-count:4; /* split it into 5 columns */
                -webkit-column-gap:8px; /* give it a 5px gap between columns */
                -moz-column-count:4;
                -moz-column-gap:8px;
                column-count:4;
                column-gap:8px;
                padding: 0 20px;">
        {% for movie in object_list %}
            <div>
                <a href="{% url 'movies:detail' slug=movie.slug %}">
                <img src="{{movie.thumb.url}}" style="width: 100% ;
                                            height: auto ;
                                            margin-bottom:  8px;
                                            cursor: pointer;
                                            border: 1px solid white;" >
                </a>
            </div>
        <!-- {% empty %} -->
        {% endfor %}
    </div>
    {% else %}
        <div style="padding: 0 50px;  ;font-size:40px;color:white; text-shadow:3px 3px black">Sorry :( No movies found.</div>
    {% endif %}
{% endblock %}

Moviement/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Moviement</title>
</head>
<body style="overflow: scroll;overflow-x:hidden;">
    <div class="wrapper">
        <div class="nav-bar">
            <div class="logo">
                <a href="{% url 'movies:list' %}"><img src="{% static 'logo.png' %}" ></a>
            </div>
            {% if  user.is_authenticated %}
                <div class="search_bar" style="padding:10px;display:flex;">
                    <form action="{% url 'movies:search_results' %}" method="GET">
                        {% csrf_token %}
                        <input name="que" type="text" placeholder="Search..." style="padding: 10px;
                                                                                    font-size: 17px;
                                                                                    border: 1px solid grey;
                                                                                    background: rgba(0,0,0,0.8);
                                                                                    color:white">
                        <button type="submit" style="padding: 10px;
                                                    font-size: 17px;
                                                    border: 1px solid grey;
                                                    background: rgba(255,0,0,0.9);
                                                    margin-left:-5px">
                                                    <i class="fa fa-search" style="color: white;
                                                                                    border-left: none;
                                                                                    cursor: pointer;">
                                                    </i>
                        </button>
                    </form>
                </div>
            {% endif %}
            <div class="accounts">
                {% if user.is_authenticated %}
                    <div class="greeting" style="display: flex;padding:0 25px">
                        <div class="symbol" style="font-size: 30px;">&#128075</div>
                        <div class="name_of_user" style="display: inline;margin:-10px 5px"><h2>{{user.username}}</h2></div>
                    </div>
                    <form class="logout-form" method="post" action="{% url 'accounts:logout'%}">
                        {% csrf_token %}
                        <input class="logout-button" type="submit" value="Logout" style="font-size: 15px;cursor:pointer">
                    </form>
                {% else %}
                    <div class="login-button"><a href="{% url 'accounts:login' %}">Login</a></div>
                    <div class="signup-button"><a href="{% url 'accounts:signup' %}">Signup</a></div>
                {% endif %}

            </div>
        </div>
        {% if not user.is_authenticated %}
        <div class="middle-container">
            <div class="middle-part">
                <h1>Enjoy the unlimited</h1>
                <h1>Movies and TV shows</h1>
                <h1>for free...</h1>
            </div>
        </div>
        {% else %}
            <div>
                {% block content %}
                {% endblock %}

            </div>
        {% endif %}
    </div>
</body>
</html>

Moviement/templates/most_basic_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Moviement</title>
</head>
<body style="overflow: scroll;overflow-x:hidden">
    <div class="wrapper">
        <div class="nav-bar">
            <div class="logo">
                <img src="{% static 'logo.png' %}" >
            </div>
            <div class="accounts">
                {% if user.is_authenticated %}
                    <div class="greeting">
                        <p>&#128075</p>
                        <h3>{{user.username}}</h3>
                    </div>
                    <form class="logout-form" method="post" action="{% url 'accounts:logout'%}">
                        {% csrf_token %}
                        <input class="logout-button" type="submit" value="Logout">
                    </form>
                {% else %}
                    <div class="login-button"><a href="{% url 'accounts:login' %}">Login</a></div>
                    <div class="signup-button"><a href="{% url 'accounts:signup' %}">Signup</a></div>
                {% endif %}

            </div>
        </div>
            {% block content %}
            {% endblock %}
    </div>
</body>
</html>